{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "901ec3f7-441f-4d71-9719-2ba5875ddd32",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import time\n",
    "from datetime import datetime, timedelta\n",
    "import pandas as pd\n",
    "import os\n",
    "import numpy as np\n",
    "\n",
    "# ==========================\n",
    "# TELEGRAM CONFIG\n",
    "# ==========================\n",
    "\n",
    "BOT_TOKEN = os.getenv(\"BOT_TOKEN\")\n",
    "\n",
    "chat_ids = [\n",
    "    \"5034473353\"\n",
    "]\n",
    "\n",
    "def send_message(text):\n",
    "    for chat_id in chat_ids:\n",
    "        url = f\"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage\"\n",
    "        payload = {\n",
    "            \"chat_id\": chat_id,\n",
    "            \"text\": text\n",
    "        }\n",
    "        requests.post(url, data=payload)\n",
    "\n",
    "# ==========================\n",
    "# WAIT FUNCTION\n",
    "# ==========================\n",
    "\n",
    "def wait_until_next_run():\n",
    "    now = datetime.now()\n",
    "\n",
    "    if now.minute < 30:\n",
    "        target = now.replace(minute=30, second=0, microsecond=0)\n",
    "    else:\n",
    "        target = (now + timedelta(hours=1)).replace(minute=0, second=0, microsecond=0)\n",
    "\n",
    "    sleep_seconds = (target - now).total_seconds()\n",
    "\n",
    "    # ✅ Added 10 second delay to ensure candle is fully closed\n",
    "    time.sleep(sleep_seconds + 10)\n",
    "\n",
    "# ==========================\n",
    "# RSI FUNCTION\n",
    "# ==========================\n",
    "\n",
    "def calculate_rsi(series, length=14):\n",
    "    delta = series.diff()\n",
    "\n",
    "    gain = np.where(delta > 0, delta, 0)\n",
    "    loss = np.where(delta < 0, -delta, 0)\n",
    "\n",
    "    gain = pd.Series(gain, index=series.index)\n",
    "    loss = pd.Series(loss, index=series.index)\n",
    "\n",
    "    avg_gain = gain.ewm(alpha=1/length, adjust=False).mean()\n",
    "    avg_loss = loss.ewm(alpha=1/length, adjust=False).mean()\n",
    "\n",
    "    rs = avg_gain / avg_loss\n",
    "    rsi = 100 - (100 / (1 + rs))\n",
    "\n",
    "    return rsi\n",
    "\n",
    "\n",
    "# ==========================\n",
    "# BOT LOOP\n",
    "# ==========================\n",
    "\n",
    "last_signal = None\n",
    "symbol = \"ETHUSDT\"\n",
    "\n",
    "while True:\n",
    "\n",
    "    print(\"Running at:\", datetime.now())\n",
    "\n",
    "    end = int(time.time())\n",
    "    start = end - 200 * 1800\n",
    "\n",
    "    url = \"https://api.delta.exchange/v2/history/candles\"\n",
    "\n",
    "    params = {\n",
    "        \"symbol\": symbol,\n",
    "        \"resolution\": \"30m\",\n",
    "        \"start\": start,\n",
    "        \"end\": end\n",
    "    }\n",
    "\n",
    "    response = requests.get(url, params=params)\n",
    "    data = response.json()\n",
    "\n",
    "    candles = data[\"result\"]\n",
    "\n",
    "    df = pd.DataFrame(candles)\n",
    "\n",
    "    df.rename(columns={\n",
    "        \"time\": \"Open_time\",\n",
    "        \"open\": \"Open\",\n",
    "        \"high\": \"High\",\n",
    "        \"low\": \"Low\",\n",
    "        \"close\": \"Close\",\n",
    "        \"volume\": \"Volume\"\n",
    "    }, inplace=True)\n",
    "\n",
    "    df[\"Open_time\"] = pd.to_datetime(df[\"Open_time\"], unit='s')\n",
    "    df = df.sort_values(\"Open_time\")\n",
    "    df.reset_index(drop=True, inplace=True)\n",
    "\n",
    "    for col in [\"Open\", \"High\", \"Low\", \"Close\", \"Volume\"]:\n",
    "        df[col] = df[col].astype(float)\n",
    "\n",
    "    df = df.loc[:, ['Open_time', 'Open', 'Close', 'High', 'Low', 'Volume']]\n",
    "\n",
    "    df['Open_time'] = pd.to_datetime(df['Open_time'])\n",
    "\n",
    "    df['Open_time'] = (\n",
    "        df['Open_time']\n",
    "        .dt.tz_localize('UTC')\n",
    "        .dt.tz_convert('Asia/Kolkata')\n",
    "        .dt.tz_localize(None)\n",
    "    )\n",
    "\n",
    "    df2 = df.copy()\n",
    "\n",
    "    # ==========================\n",
    "    # CCI\n",
    "    # ==========================\n",
    "\n",
    "    df2[\"hlc3\"] = (df2[\"High\"] + df2[\"Low\"] + df2[\"Close\"]) / 3\n",
    "    df2[\"ma\"] = df2[\"hlc3\"].rolling(window=60).mean()\n",
    "\n",
    "    df2[\"mean_dev\"] = df2[\"hlc3\"].rolling(window=60).apply(\n",
    "        lambda x: np.mean(np.abs(x - np.mean(x))), raw=True\n",
    "    )\n",
    "\n",
    "    df2[\"CCI_60\"] = (df2[\"hlc3\"] - df2[\"ma\"]) / (0.015 * df2[\"mean_dev\"])\n",
    "\n",
    "    df2[\"CCI_EMA\"] = df2[\"CCI_60\"].ewm(span=7, adjust=False).mean()\n",
    "\n",
    "    df2['OUTPUT'] = np.where(df2['CCI_60'] > df2.CCI_EMA, 'Pass', 'Fail')\n",
    "    df2['Decision'] = np.where(df2['CCI_60'] > df2.CCI_EMA, 'Long', 'Short')\n",
    "\n",
    "    # EMA\n",
    "    df2[\"EMA7\"] = df2[\"Close\"].ewm(span=7, adjust=False).mean()\n",
    "    df2['EMA7_CROSS'] = np.where(df2[\"Close\"] > df2['EMA7'], 'Pass', 'Fail')\n",
    "\n",
    "    # RSI\n",
    "    df2['RSI'] = calculate_rsi(df2[\"Close\"])\n",
    "    df2['RSI_OUTPUT'] = np.where(df2['RSI'] > 40, 'Pass', 'Fail')\n",
    "\n",
    "    # Difference\n",
    "    df2['Diff_CCI'] = df2.CCI_60 - df2.CCI_EMA\n",
    "\n",
    "    # ==========================\n",
    "    # SIGNAL\n",
    "    # ==========================\n",
    "\n",
    "    df2['Signal'] = np.where(\n",
    "        (df2['OUTPUT'] == 'Pass') & (abs(df2['Diff_CCI']) > 4) & (df2['EMA7_CROSS'] == 'Pass'),\n",
    "        'Long Entry',\n",
    "        np.where(\n",
    "            (df2['OUTPUT'] == 'Fail') & (abs(df2['Diff_CCI']) > 4) & (df2['EMA7_CROSS'] == 'Fail'),\n",
    "            'Short Entry',\n",
    "            'No Trade'\n",
    "        )\n",
    "    )\n",
    "\n",
    "    filtered_df = df2[[\"Open_time\", \"Signal\", \"Close\"]]\n",
    "\n",
    "    latest = filtered_df.tail(2).iloc[0]\n",
    "\n",
    "    open_time = latest[\"Open_time\"].strftime(\"%Y-%m-%d %H:%M\")\n",
    "    close = latest[\"Close\"]\n",
    "    signal = latest[\"Signal\"]\n",
    "\n",
    "    if signal != last_signal:\n",
    "\n",
    "        msg = f\"\"\"\n",
    "🚨 Trading Signal\n",
    "Time: {open_time}\n",
    "Closing Price: {close}\n",
    "Signal: {signal}\n",
    "\"\"\"\n",
    "\n",
    "        send_message(msg)\n",
    "\n",
    "        data = {\n",
    "            \"Open_time\": [open_time],\n",
    "            \"Closing Price\": [close],\n",
    "            \"Signal\": [signal]\n",
    "        }\n",
    "\n",
    "        df_save = pd.DataFrame(data)\n",
    "\n",
    "        file = \"signals.xlsx\"\n",
    "\n",
    "        if not os.path.exists(file):\n",
    "            df_save.to_excel(file, index=False)\n",
    "        else:\n",
    "            with pd.ExcelWriter(file, mode=\"a\", engine=\"openpyxl\", if_sheet_exists=\"overlay\") as writer:\n",
    "                df_save.to_excel(\n",
    "                    writer,\n",
    "                    index=False,\n",
    "                    header=False,\n",
    "                    startrow=writer.sheets[\"Sheet1\"].max_row\n",
    "                )\n",
    "\n",
    "        last_signal = signal\n",
    "\n",
    "    wait_until_next_run()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
